name: Create GitHub Release on Tag Creation

on:
  push:
    tags:
      - '*'  # Trigger only when a new tag is created

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            # Specify files to be attached to the release if needed (e.g., dist/*)
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Announce Release
        run: |
          echo "Release created for tag ${GITHUB_REF#refs/tags/}!"
