name: Publish on PR Merge

on:
  pull_request:
    types: [closed]
    branches:
      - develop
      - master

jobs:
  publish:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'version-update/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: "Create .npmrc"
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: bun install

      - name: Build packages
        run: |
          for pkg in packages/*; do
            if [ -f "$pkg/package.json" ]; then
              cd $pkg
              bun run build
              cd ../..
            fi
          done

      - name: Publish to NPM
        run: |
          BRANCH=${{ github.base_ref }}
          for pkg in packages/*; do
            if [ -f "$pkg/package.json" ]; then
              cd $pkg
              if [ "$BRANCH" = "develop" ]; then
                npm publish --tag canary
              else
                npm publish
              fi
              cd ../..
            fi
          done

      - name: Create Release
        if: github.base_ref == 'master'
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ fromJson(github.event.pull_request.title).version }}
          name: ${{ github.event.pull_request.title }}
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}