name: Release

on:
  push:
    branches:
      - develop
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  release:
    name: Release
    # Only run on merged PRs to master or pushes to develop
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.merge_commit_sha || github.sha }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Create Release PR
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          default-branch: master
          pull-request-title-pattern: "chore: release ${version}"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: bunx multi-semantic-release