name: Release
permissions:
  contents: write
  packages: write
on:
  # For develop branch and version maintenance branches
  push:
    branches:
      - develop
      - 'version-[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      packages: write
    
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Install Dependencies
        run: bun install
      
      - name: Build
        run: bun run build
      
      - name: Set Git User
        run: |
          git config --global user.email ""
          git config --global user.name "mantou-action-bot"
      
      - name: Version and Publish
        uses: ./.github/actions/version-and-publish
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ steps.app-token.outputs.token }}