name: Publish Packages

on:
  push:
    branches:
      - develop
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write

    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=${GH_TOKEN}" >> .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies
        run: bun install

      - name: Get commit messages
        id: get_commits
        run: |
          COMMITS=$(git log --format="%s" $(git describe --tags --abbrev=0 2>/dev/null || git rev-list --max-parents=0 HEAD)..HEAD)
          echo "commits<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Determine version
        id: version
        run: |
          BRANCH="${{ github.event_name == 'pull_request' && 'master' || github.ref_name }}"
          
          # Get the latest version from npm for all packages
          LATEST_VERSIONS=()
          for pkg in packages/*; do
            if [ -f "$pkg/package.json" ]; then
              PKG_NAME=$(node -p "require('./$pkg/package.json').name")
              LATEST_VERSION=$(npm view $PKG_NAME version 2>/dev/null || echo "0.0.0")
              LATEST_VERSIONS+=($LATEST_VERSION)
            fi
          done
          
          # Find the highest version
          LATEST_VERSION=$(printf '%s\n' "${LATEST_VERSIONS[@]}" | sort -V | tail -n1)
          
          # Analyze commits to determine version bump
          COMMITS="${{ steps.get_commits.outputs.commits }}"
          
          if echo "$COMMITS" | grep -q "^feat!:\|^BREAKING CHANGE"; then
            # Major version for breaking changes
            NEW_BASE_VERSION=$(echo $LATEST_VERSION | awk -F. '{$1++; $2=0; $3=0; print $1"."$2"."$3}' OFS=.)
          elif echo "$COMMITS" | grep -q "^feat:"; then
            # Minor version for features
            NEW_BASE_VERSION=$(echo $LATEST_VERSION | awk -F. '{$2++; $3=0; print $1"."$2"."$3}' OFS=.)
          else
            # Patch version for fixes
            NEW_BASE_VERSION=$(echo $LATEST_VERSION | awk -F. '{$3++; print $1"."$2"."$3}' OFS=.)
          fi
          
          if [ "$BRANCH" = "develop" ]; then
            NEW_VERSION="${NEW_BASE_VERSION}-canary.1"
          else
            NEW_VERSION="${NEW_BASE_VERSION}"
          fi
          
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update versions
        run: |
          NEW_VERSION=${{ steps.version.outputs.new_version }}
          
          # Update root package.json
          if [ -f "package.json" ]; then
            sed -i "s/\"version\": \".*\"/\"version\": \"$NEW_VERSION\"/" package.json
          fi
          
          # Update all package versions in packages directory
          for pkg in packages/*; do
            if [ -f "$pkg/package.json" ]; then
              sed -i "s/\"version\": \".*\"/\"version\": \"$NEW_VERSION\"/" $pkg/package.json
              
              # Update internal dependencies versions
              PKG_NAME=$(node -p "require('./$pkg/package.json').name")
              for dep_pkg in packages/*; do
                if [ -f "$dep_pkg/package.json" ]; then
                  sed -i "s/\"$PKG_NAME\": \".*\"/\"$PKG_NAME\": \"$NEW_VERSION\"/" $dep_pkg/package.json
                fi
              done
            fi
          done

      - name: Push develop version
        if: github.event_name == 'push'
        run: |
          NEW_VERSION=${{ steps.version.outputs.new_version }}
          git add package.json packages/*/package.json
          git commit -m "chore: update version to ${NEW_VERSION} [skip ci]"
          git push origin develop

      - name: Push master version and create stable tag
        if: github.event_name == 'pull_request'
        run: |
          NEW_VERSION=${{ steps.version.outputs.new_version }}
          
          # Create and push version commit
          git add package.json packages/*/package.json
          git commit -m "chore: update version to ${NEW_VERSION} [skip ci]"
          git push origin master
          
          # Create and push stable tag
          git tag -a "v${NEW_VERSION}" -m "Release v${NEW_VERSION}"
          git tag -a "stable" -m "Latest stable release v${NEW_VERSION}" -f
          git push origin "v${NEW_VERSION}"
          git push origin stable -f

      - name: Build packages
        run: |
          for pkg in packages/*; do
            if [ -f "$pkg/package.json" ]; then
              cd $pkg
              bun run build
              cd ../..
            fi
          done

      - name: Publish to NPM
        run: |
          for pkg in packages/*; do
            if [ -f "$pkg/package.json" ]; then
              cd $pkg
              if [ "${{ github.event_name }}" = "push" ]; then
                npm publish --tag canary
              else
                npm publish --tag latest
                npm dist-tag add "$(node -p "require('./package.json').name")@${{ steps.version.outputs.new_version }}" stable
              fi
              cd ../..
            fi
          done

      - name: Create GitHub Release
        if: github.event_name == 'pull_request'
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ steps.version.outputs.new_version }}
          name: Release v${{ steps.version.outputs.new_version }}
          generateReleaseNotes: true
          makeLatest: true
          token: ${{ secrets.GH_TOKEN }}